apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: hello-world-image
spec:
  tag: junyimsft/kpack-generated-hello-world
  serviceAccount: dockerhub-service-account
  builder:
    name: base-builder
    kind: Builder
  source:
    git:
      url: https://github.com/JunyiYi/kpack-introduction-demo.git
      revision: main
    subPath: HelloWorld
